# -*- coding: utf-8 -*-
"""Execute, Observe, Self-Correct: The Core Agent Loop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aZ_whpZxEZ2vgf9Toj7AUZPTVeRpB73x
"""

# ============================================================
# WEEK 2 - EXECUTE, OBSERVE, SELF-CORRECT
# AI CODING AGENT
# ============================================================

# Install Groq
!pip -q install groq

# ------------------------------------------------------------
# 1. IMPORTS AND API SETUP
# ------------------------------------------------------------

import os
import re
import tempfile
import subprocess
from getpass import getpass
from pathlib import Path

from groq import Groq

print("=" * 70)
print("WEEK 2 - AI CODING AGENT")
print("=" * 70)

# Enter API key securely
if "GROQ_API_KEY" not in os.environ:
    os.environ["GROQ_API_KEY"] = getpass(
        "Enter your Groq API key: "
    )

client = Groq(api_key=os.environ["GROQ_API_KEY"])

MODEL = "openai/gpt-oss-120b"
MAX_ATTEMPTS = 3
TIMEOUT = 8


# ------------------------------------------------------------
# 2. SYSTEM PROMPT
# ------------------------------------------------------------

SYSTEM_PROMPT = """
You are an expert Python coding agent.

Your job is to write Python code that solves the user's task.

IMPORTANT RULES:
1. Return ONLY Python code.
2. Do NOT return explanations.
3. Do NOT use Markdown code fences.
4. The code must be directly executable.
5. Follow every requirement in the user's task.
6. The user's task may contain assert statements.
7. The generated code must make all assertions pass.
8. If previous code failed, carefully analyze the error and fix it.
"""


# ------------------------------------------------------------
# 3. CLEAN LLM RESPONSE
# ------------------------------------------------------------

def clean_code(code):
    code = code.strip()

    # Remove Markdown code fences if the model adds them
    code = re.sub(
        r"^```(?:python)?\s*",
        "",
        code,
        flags=re.IGNORECASE
    )

    code = re.sub(r"\s*```$", "", code)

    return code.strip()


# ------------------------------------------------------------
# 4. GENERATE OR REPAIR CODE
# ------------------------------------------------------------

def generate_code(task, previous_code=None, error=None):

    if previous_code and error:

        prompt = f"""
Original task:

{task}

The previous generated code was:

{previous_code}

The previous execution failed.

Here is the execution output/error:

{error}

Analyze the failure and fix the Python code.

Make sure the original task and ALL assertions are satisfied.

Return ONLY the corrected Python code.
"""

    else:
        prompt = task

    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {
                "role": "system",
                "content": SYSTEM_PROMPT
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0.2,
        max_completion_tokens=4096
    )

    return clean_code(
        response.choices[0].message.content
    )


# ------------------------------------------------------------
# 5. SAFE CODE EXECUTION
# ------------------------------------------------------------

def execute_code(code, timeout=8):

    # Create a temporary Python file
    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".py",
        delete=False,
        encoding="utf-8"
    ) as temp_file:

        temp_file.write(code)
        temp_path = temp_file.name

    try:

        # IMPORTANT:
        # We do NOT use eval() or exec().
        # Code runs in a separate Python subprocess.
        result = subprocess.run(
            ["python", temp_path],
            capture_output=True,
            text=True,
            timeout=timeout
        )

        return {
            "passed": result.returncode == 0,
            "return_code": result.returncode,
            "stdout": result.stdout,
            "stderr": result.stderr
        }

    except subprocess.TimeoutExpired:

        return {
            "passed": False,
            "return_code": -1,
            "stdout": "",
            "stderr": "Execution timed out."
        }

    except Exception as e:

        return {
            "passed": False,
            "return_code": -1,
            "stdout": "",
            "stderr": str(e)
        }

    finally:

        # Delete temporary file
        try:
            os.remove(temp_path)
        except:
            pass


# ------------------------------------------------------------
# 6. CORE AGENT LOOP
# ------------------------------------------------------------

def run_agent(task, max_attempts=3):

    previous_code = None
    error = None

    for attempt in range(1, max_attempts + 1):

        print("\n")
        print("=" * 70)
        print(f"ATTEMPT {attempt}/{max_attempts}")
        print("=" * 70)

        # Generate or repair code
        code = generate_code(
            task,
            previous_code,
            error
        )

        print("\nGENERATED CODE")
        print("-" * 70)
        print(code)
        print("-" * 70)

        # Execute generated code
        result = execute_code(
            code,
            timeout=TIMEOUT
        )

        print("\nEXECUTION OUTPUT")

        if result["stdout"]:
            print(result["stdout"])

        if result["stderr"]:
            print(result["stderr"])

        print(f"Return code: {result['return_code']}")

        # ----------------------------------------------------
        # SUCCESS
        # ----------------------------------------------------

        if result["passed"]:

            print("\n" + "=" * 70)
            print("PASS")
            print(f"Agent succeeded on attempt {attempt}.")
            print("=" * 70)

            return {
                "success": True,
                "attempts": attempt,
                "code": code,
                "result": result
            }

        # ----------------------------------------------------
        # FAILURE
        # ----------------------------------------------------

        print("\n" + "=" * 70)
        print("FAIL")
        print("Sending error back to the LLM for self-correction...")
        print("=" * 70)

        previous_code = code

        error = (
            f"STDOUT:\n{result['stdout']}\n\n"
            f"STDERR:\n{result['stderr']}\n\n"
            f"RETURN CODE:\n{result['return_code']}"
        )

    # --------------------------------------------------------
    # MAX ATTEMPTS REACHED
    # --------------------------------------------------------

    print("\n" + "=" * 70)
    print("AGENT FAILED")
    print("Maximum number of attempts reached.")
    print("=" * 70)

    return {
        "success": False,
        "attempts": max_attempts,
        "code": previous_code,
        "result": result
    }


# ============================================================
# 7. FIVE REQUIRED TEST TASKS
# ============================================================

tasks = [

    # TEST 1
    """
Write a function called reverse_string(s) that returns
the reversed string.

It must pass:

assert reverse_string("abc") == "cba"
assert reverse_string("hello") == "olleh"
assert reverse_string("") == ""
""",

    # TEST 2
    """
Write a function called is_prime(n) that returns True if
n is a prime number and False otherwise.

It must pass:

assert is_prime(2) == True
assert is_prime(7) == True
assert is_prime(10) == False
assert is_prime(1) == False
""",

    # TEST 3
    """
Write a function called remove_duplicates(items) that removes
duplicate values from a list while preserving the original order.

It must pass:

assert remove_duplicates([1, 2, 2, 3, 1]) == [1, 2, 3]
assert remove_duplicates(["a", "b", "a"]) == ["a", "b"]
""",

    # TEST 4
    """
Write a function called word_frequency(text) that returns a
dictionary containing the number of occurrences of each word.

Words are separated by spaces.

It must pass:

assert word_frequency("apple banana apple") == {
    "apple": 2,
    "banana": 1
}
""",

    # TEST 5
    """
Write a function called factorial(n) that returns the factorial
of n.

It must pass:

assert factorial(0) == 1
assert factorial(1) == 1
assert factorial(5) == 120
assert factorial(6) == 720
"""
]


# ============================================================
# 8. RUN ALL FIVE TESTS
# ============================================================

results = []

for number, task in enumerate(tasks, 1):

    print("\n\n")
    print("#" * 70)
    print(f"TEST {number}")
    print("#" * 70)

    result = run_agent(
        task,
        max_attempts=MAX_ATTEMPTS
    )

    results.append(result)


# ============================================================
# 9. TEST SUMMARY
# ============================================================

print("\n\n")
print("=" * 70)
print("WEEK 2 TEST SUMMARY")
print("=" * 70)

for i, result in enumerate(results, 1):

    status = "PASS" if result["success"] else "FAIL"

    print(
        f"Test {i}: {status} | "
        f"Attempts: {result['attempts']}"
    )


# ============================================================
# 10. SAVE LAST SUCCESSFUL CODE
# ============================================================

successful_results = [
    r for r in results
    if r["success"]
]

if successful_results:

    final_code = successful_results[-1]["code"]

    with open("generated_code.py", "w", encoding="utf-8") as f:
        f.write(final_code)

    print("\nGenerated code saved to:")
    print("generated_code.py")


# ============================================================
# 11. OPTIONAL SELF-CORRECTION DEMO
# ============================================================

print("\n\n")
print("=" * 70)
print("SELF-CORRECTION DEMO")
print("=" * 70)

demo_task = """
Write a function called divide_numbers(a, b) that returns a / b.

The function must handle division by zero by returning 0.

It must pass:

assert divide_numbers(10, 2) == 5
assert divide_numbers(10, 5) == 2
assert divide_numbers(10, 0) == 0
"""

demo_result = run_agent(
    demo_task,
    max_attempts=3
)


# ============================================================
# 12. FINAL STATUS
# ============================================================

print("\n\n")
print("=" * 70)
print("WEEK 2 COMPLETE")
print("=" * 70)

passed = sum(
    1 for r in results
    if r["success"]
)

print(f"Required tests passed: {passed}/{len(results)}")

if demo_result["success"]:
    print(
        f"Self-correction demo passed in "
        f"{demo_result['attempts']} attempt(s)."
    )
else:
    print("Self-correction demo did not pass.")

print("\nArchitecture:")
print("Natural Language")
print("      ↓")
print("LLM Code Generation")
print("      ↓")
print("Temporary .py File")
print("      ↓")
print("subprocess.run() + timeout")
print("      ↓")
print("Observe stdout / stderr")
print("      ↓")
print("PASS → Finish")
print("      ↓")
print("FAIL → Send error to LLM")
print("      ↓")
print("Retry (maximum 3 attempts)")