# -*- coding: utf-8 -*-
"""MULTI-FILE CONTEXT CODE AGENT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16qKtwhJiawAY6W5YE9IWF3pFskcT4YP7
"""

# ============================================================
# WEEK 3 - MULTI-FILE CONTEXT CODE AGENT
# ============================================================

!pip -q install groq

import os
import re
import ast
import json
import shutil
import tempfile
import subprocess
from pathlib import Path
from getpass import getpass

from groq import Groq


# ============================================================
# 1. GROQ SETUP
# ============================================================

if "GROQ_API_KEY" not in os.environ:
    os.environ["GROQ_API_KEY"] = getpass(
        "Enter your Groq API key: "
    )

client = Groq(api_key=os.environ["GROQ_API_KEY"])

MODEL = "openai/gpt-oss-120b"

PROJECT_DIR = Path("sample_project")
BACKUP_DIR = Path("backup_before_edit")


# ============================================================
# 2. CREATE SAMPLE PROJECT
# ============================================================

PROJECT_DIR.mkdir(exist_ok=True)

calculator_code = '''
def add(a, b):
    """Return the sum of two numbers."""
    return a + b


def subtract(a, b):
    """Return the difference between two numbers."""
    return a - b


def multiply(a, b):
    """Return the product of two numbers."""
    return a * b


def divide(a, b):
    """Return a divided by b."""
    return a / b
'''

test_code = '''
from calculator import add, subtract, multiply, divide


assert add(2, 3) == 5
assert subtract(5, 3) == 2
assert multiply(4, 5) == 20
assert divide(10, 2) == 5

print("All tests passed!")
'''

main_code = '''
from calculator import add, subtract, multiply, divide


def main():
    print("Calculator Demo")

    print("2 + 3 =", add(2, 3))
    print("5 - 3 =", subtract(5, 3))
    print("4 * 5 =", multiply(4, 5))
    print("10 / 2 =", divide(10, 2))


if __name__ == "__main__":
    main()
'''

(PROJECT_DIR / "calculator.py").write_text(
    calculator_code.strip() + "\n",
    encoding="utf-8"
)

(PROJECT_DIR / "test_calculator.py").write_text(
    test_code.strip() + "\n",
    encoding="utf-8"
)

(PROJECT_DIR / "main.py").write_text(
    main_code.strip() + "\n",
    encoding="utf-8"
)

print("Sample project created:")
for file in PROJECT_DIR.iterdir():
    print(" -", file)


# ============================================================
# 3. READ PROJECT FILES
# ============================================================

def read_project_files(project_dir):

    files = {}

    for file in project_dir.glob("*.py"):
        files[file.name] = file.read_text(
            encoding="utf-8"
        )

    return files


# ============================================================
# 4. BUILD FILE CONTEXT SUMMARY
# ============================================================

def summarize_python_file(code):

    try:
        tree = ast.parse(code)
    except SyntaxError:
        return "Unable to parse Python file."

    functions = []
    classes = []
    imports = []

    for node in ast.walk(tree):

        if isinstance(node, ast.FunctionDef):
            args = [
                arg.arg
                for arg in node.args.args
            ]

            functions.append(
                f"{node.name}({', '.join(args)})"
            )

        elif isinstance(node, ast.ClassDef):
            classes.append(node.name)

        elif isinstance(node, ast.Import):
            for alias in node.names:
                imports.append(alias.name)

        elif isinstance(node, ast.ImportFrom):
            if node.module:
                imports.append(node.module)

    summary = []

    if functions:
        summary.append(
            "Functions: " + ", ".join(functions)
        )

    if classes:
        summary.append(
            "Classes: " + ", ".join(classes)
        )

    if imports:
        summary.append(
            "Imports: " + ", ".join(imports)
        )

    if not summary:
        summary.append("No functions or classes found.")

    return "\n".join(summary)


def build_project_context(files):

    context = []

    for filename, code in files.items():

        summary = summarize_python_file(code)

        context.append(
            f"""
FILE: {filename}

SUMMARY:
{summary}
"""
        )

    return "\n".join(context)


# ============================================================
# 5. DISPLAY PROJECT CONTEXT
# ============================================================

files = read_project_files(PROJECT_DIR)

context = build_project_context(files)

print("\n")
print("=" * 70)
print("PROJECT CONTEXT")
print("=" * 70)
print(context)


# ============================================================
# 6. USER TASK
# ============================================================

TASK = """
Add input validation to the divide function so that it raises
ValueError when division by zero is attempted.

Also update the test_calculator.py file to test this behavior.

The existing successful tests must continue to pass.
"""


# ============================================================
# 7. ASK LLM WHICH FILES NEED TO CHANGE
# ============================================================

PLANNING_PROMPT = f"""
You are an AI coding agent working on a small Python project.

PROJECT CONTEXT:

{context}

USER REQUEST:

{TASK}

Identify which files need to be changed.

Return ONLY a JSON object in this exact format:

{{
    "files_to_edit": ["calculator.py", "test_calculator.py"],
    "reason": "short explanation"
}}
"""

response = client.chat.completions.create(
    model=MODEL,
    messages=[
        {
            "role": "system",
            "content": (
                "You analyze Python projects and identify files "
                "that need coordinated changes."
            )
        },
        {
            "role": "user",
            "content": PLANNING_PROMPT
        }
    ],
    temperature=0
)

planning_response = response.choices[0].message.content.strip()

print("\n")
print("=" * 70)
print("AGENT FILE PLAN")
print("=" * 70)
print(planning_response)


# ============================================================
# 8. EXTRACT JSON FROM RESPONSE
# ============================================================

json_match = re.search(
    r"\{.*\}",
    planning_response,
    re.DOTALL
)

if not json_match:
    raise ValueError(
        "LLM did not return valid JSON."
    )

plan = json.loads(
    json_match.group()
)

files_to_edit = plan["files_to_edit"]

print("\nFiles selected for editing:")
for file in files_to_edit:
    print(" -", file)


# ============================================================
# 9. BACKUP ORIGINAL FILES
# ============================================================

if BACKUP_DIR.exists():
    shutil.rmtree(BACKUP_DIR)

BACKUP_DIR.mkdir()

for filename in files_to_edit:

    source = PROJECT_DIR / filename
    backup = BACKUP_DIR / filename

    shutil.copy2(source, backup)

print("\nBackups created in:", BACKUP_DIR)


# ============================================================
# 10. SEND FULL CONTENT OF RELEVANT FILES TO LLM
# ============================================================

editable_context = ""

for filename in files_to_edit:

    code = files[filename]

    editable_context += f"""

============================================================
FILE: {filename}
============================================================

{code}
"""


# ============================================================
# 11. ASK LLM TO EDIT MULTIPLE FILES
# ============================================================

EDIT_PROMPT = f"""
You are an expert Python coding agent.

The user wants this change:

{TASK}

The following files were identified as relevant:

{editable_context}

Modify ALL necessary files so the request is correctly implemented.

Requirements:
1. Preserve existing functionality.
2. Update tests where required.
3. Make sure imports remain correct.
4. Make sure all existing tests continue to pass.
5. Add a test for division by zero.
6. The divide function must raise ValueError when b == 0.
7. Return ONLY JSON.
8. Do not use Markdown code fences.

Return exactly this structure:

{{
    "files": {{
        "filename.py": "complete new file content"
    }}
}}
"""

response = client.chat.completions.create(
    model=MODEL,
    messages=[
        {
            "role": "system",
            "content": (
                "You modify multi-file Python projects. "
                "Return complete file contents as JSON."
            )
        },
        {
            "role": "user",
            "content": EDIT_PROMPT
        }
    ],
    temperature=0.1,
    max_completion_tokens=8000
)

edit_response = response.choices[0].message.content.strip()

print("\n")
print("=" * 70)
print("LLM EDIT RESPONSE")
print("=" * 70)

print(edit_response)


# ============================================================
# 12. PARSE EDIT RESPONSE
# ============================================================

json_match = re.search(
    r"\{.*\}",
    edit_response,
    re.DOTALL
)

if not json_match:
    raise ValueError(
        "LLM did not return valid edit JSON."
    )

edit_data = json.loads(
    json_match.group()
)


# ============================================================
# 13. APPLY MULTI-FILE CHANGES
# ============================================================

for filename, new_content in edit_data["files"].items():

    target = PROJECT_DIR / filename

    if filename not in files_to_edit:
        print(
            f"Skipping unexpected file: {filename}"
        )
        continue

    target.write_text(
        new_content,
        encoding="utf-8"
    )

    print(
        f"Updated: {target}"
    )


# ============================================================
# 14. SHOW BEFORE / AFTER
# ============================================================

print("\n")
print("=" * 70)
print("BEFORE / AFTER")
print("=" * 70)

for filename in files_to_edit:

    print("\n")
    print("#" * 70)
    print(f"FILE: {filename}")
    print("#" * 70)

    print("\n--- BEFORE ---")
    print(
        (BACKUP_DIR / filename).read_text(
            encoding="utf-8"
        )
    )

    print("\n--- AFTER ---")
    print(
        (PROJECT_DIR / filename).read_text(
            encoding="utf-8"
        )
    )


# ============================================================
# 15. SAFE TEST EXECUTION
# ============================================================

def run_tests(project_dir, timeout=8):

    test_file = project_dir / "test_calculator.py"

    try:

        result = subprocess.run(
            ["python", test_file.name],
            cwd=str(project_dir),
            capture_output=True,
            text=True,
            timeout=timeout
        )

        return {
            "passed": result.returncode == 0,
            "return_code": result.returncode,
            "stdout": result.stdout,
            "stderr": result.stderr
        }

    except subprocess.TimeoutExpired:

        return {
            "passed": False,
            "return_code": -1,
            "stdout": "",
            "stderr": "Test execution timed out."
        }


# ============================================================
# 16. RUN UPDATED TESTS
# ============================================================

print("\n")
print("=" * 70)
print("RUNNING UPDATED TESTS")
print("=" * 70)

test_result = run_tests(PROJECT_DIR)

if test_result["stdout"]:
    print(test_result["stdout"])

if test_result["stderr"]:
    print(test_result["stderr"])

print(
    f"Return code: {test_result['return_code']}"
)

if test_result["passed"]:

    print("\n" + "=" * 70)
    print("✅ ALL TESTS PASSED")
    print("=" * 70)

else:

    print("\n" + "=" * 70)
    print("❌ TESTS FAILED")
    print("=" * 70)


# ============================================================
# 17. EXPLICIT DIVISION-BY-ZERO TEST
# ============================================================

print("\n")
print("=" * 70)
print("DIVISION-BY-ZERO TEST")
print("=" * 70)

division_test = """
from calculator import divide

try:
    divide(10, 0)
    print("FAIL: ValueError was not raised")
except ValueError:
    print("PASS: ValueError correctly raised")
"""

temp_test = PROJECT_DIR / "_division_test.py"

temp_test.write_text(
    division_test,
    encoding="utf-8"
)

try:

    result = subprocess.run(
        ["python", temp_test.name],
        cwd=str(PROJECT_DIR),
        capture_output=True,
        text=True,
        timeout=8
    )

    print(result.stdout)

    if result.stderr:
        print(result.stderr)

finally:

    temp_test.unlink(missing_ok=True)


# ============================================================
# 18. FINAL PROJECT STRUCTURE
# ============================================================

print("\n")
print("=" * 70)
print("FINAL PROJECT")
print("=" * 70)

for file in sorted(PROJECT_DIR.iterdir()):
    print("📄", file)


# ============================================================
# 19. SAVE A ZIP FOR SUBMISSION
# ============================================================

shutil.make_archive(
    "week3_project",
    "zip",
    PROJECT_DIR
)

print("\nCreated:")
print("week3_project.zip")


# ============================================================
# 20. FINAL STATUS
# ============================================================

print("\n")
print("=" * 70)
print("WEEK 3 COMPLETE")
print("=" * 70)

if test_result["passed"]:
    print("✅ Multi-file edit successful")
    print("✅ Tests passed")
    print("✅ Backup created")
    print("✅ Before/after comparison available")
    print("✅ Safe subprocess test execution used")
else:
    print("❌ Project tests need further correction")