# -*- coding: utf-8 -*-
"""Week 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aaHwIFYxkwu7AkfqiRlBNk6cZY35d5N4
"""

!pip -q install groq

import os
from getpass import getpass

os.environ["GROQ_API_KEY"] = getpass("Enter your Groq API key: ")

from groq import Groq
from pathlib import Path
import re

client = Groq(api_key=os.environ["GROQ_API_KEY"])

MODEL = "openai/gpt-oss-120b"

SYSTEM_PROMPT = """
You are an expert Python programmer.

Convert the user's natural-language programming task into correct,
runnable Python code.

Rules:
1. Return ONLY Python code.
2. Do NOT include explanations.
3. Do NOT include Markdown.
4. Do NOT use ``` code fences.
5. Write clean and readable Python.
6. Use functions when appropriate.
7. The generated code must directly solve the user's task.
"""

def clean_code(code):
    """Remove accidental Markdown code fences."""
    code = code.strip()

    code = re.sub(
        r"^```(?:python)?\s*",
        "",
        code,
        flags=re.IGNORECASE
    )

    code = re.sub(r"\s*```$", "", code)

    return code.strip()


def generate_code(task):
    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {
                "role": "system",
                "content": SYSTEM_PROMPT
            },
            {
                "role": "user",
                "content": task
            }
        ],
        temperature=0.2
    )

    generated_code = response.choices[0].message.content

    return clean_code(generated_code)

def save_code(code, filename="generated_code.py"):
    Path(filename).write_text(
        code + "\n",
        encoding="utf-8"
    )

    return filename

task = input("Describe the Python program you want: ")

if not task.strip():
    print("Please enter a task.")
else:
    try:
        code = generate_code(task)

        print("\n" + "=" * 60)
        print("GENERATED PYTHON CODE")
        print("=" * 60)
        print(code)
        print("=" * 60)

        filename = save_code(code)

        print(f"\nCode saved to: {filename}")

    except Exception as e:
        print(f"Error: {e}")

test_tasks = [
    "Write a function that checks if a number is prime.",
    "Write a function that reverses a string.",
    "Write a function that counts the vowels in a string.",
    "Write a function that calculates the factorial of a number.",
    "Write a function that finds the largest number in a list.",
    "Write a function that removes duplicate values from a list.",
    "Write a function that counts the frequency of each word in a sentence using a dictionary.",
    "Write a function that merges two dictionaries."
]

for i, task in enumerate(test_tasks, 1):
    print(f"\n{'=' * 70}")
    print(f"TEST {i}: {task}")
    print("=" * 70)

    try:
        code = generate_code(task)
        print(code)

    except Exception as e:
        print(f"Error: {e}")

from google.colab import files

files.download("generated_code.py")