# -*- coding: utf-8 -*-
"""Portfolio Coding-Agent CLI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h4FCCUXKX6A42nxmS0ZuDtbcZSqrhDOE
"""

!pip -q install groq

import os
from getpass import getpass

os.environ["GROQ_API_KEY"] = getpass("Enter your Groq API key: ")
print("✅ API key configured")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile agent.py
# 
# import argparse
# import ast
# import difflib
# import json
# import os
# import re
# import shutil
# import subprocess
# from pathlib import Path
# 
# from groq import Groq
# 
# 
# MODEL = "openai/gpt-oss-120b"
# MAX_ATTEMPTS = 3
# TIMEOUT = 10
# 
# 
# def get_client():
#     api_key = os.environ.get("GROQ_API_KEY")
#     if not api_key:
#         raise RuntimeError("GROQ_API_KEY is not set.")
#     return Groq(api_key=api_key)
# 
# 
# def read_project(project):
#     files = {}
# 
#     for path in project.rglob("*.py"):
#         if ".git" in path.parts:
#             continue
# 
#         try:
#             files[str(path.relative_to(project))] = path.read_text(
#                 encoding="utf-8"
#             )
#         except Exception:
#             pass
# 
#     return files
# 
# 
# def summarize_python(code):
#     try:
#         tree = ast.parse(code)
#     except SyntaxError:
#         return "Could not parse Python file."
# 
#     functions = []
#     classes = []
#     imports = []
# 
#     for node in ast.walk(tree):
#         if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
#             functions.append(node.name)
# 
#         elif isinstance(node, ast.ClassDef):
#             classes.append(node.name)
# 
#         elif isinstance(node, ast.Import):
#             imports.extend(alias.name for alias in node.names)
# 
#         elif isinstance(node, ast.ImportFrom):
#             if node.module:
#                 imports.append(node.module)
# 
#     return {
#         "functions": functions,
#         "classes": classes,
#         "imports": imports,
#     }
# 
# 
# def build_context(files):
#     context = {}
# 
#     for filename, code in files.items():
#         context[filename] = {
#             "summary": summarize_python(code)
#         }
# 
#     return context
# 
# 
# def extract_json(text):
#     text = text.strip()
# 
#     text = re.sub(
#         r"^```(?:json)?\s*",
#         "",
#         text,
#         flags=re.IGNORECASE
#     )
# 
#     text = re.sub(r"\s*```$", "", text)
# 
#     start = text.find("{")
#     end = text.rfind("}")
# 
#     if start == -1 or end == -1:
#         raise ValueError("No JSON object found.")
# 
#     return json.loads(text[start:end + 1])
# 
# 
# def plan_changes(client, task, context):
# 
#     prompt = f"""
# You are an AI coding agent.
# 
# User task:
# {task}
# 
# Project structure and Python summaries:
# {json.dumps(context, indent=2)}
# 
# Identify which files must be changed to complete the task.
# 
# Return ONLY valid JSON:
# 
# {{
#   "files_to_edit": ["file1.py", "file2.py"],
#   "reason": "short explanation"
# }}
# """
# 
#     response = client.chat.completions.create(
#         model=MODEL,
#         messages=[
#             {
#                 "role": "system",
#                 "content": "Return only valid JSON."
#             },
#             {
#                 "role": "user",
#                 "content": prompt
#             }
#         ],
#         temperature=0
#     )
# 
#     return extract_json(response.choices[0].message.content)
# 
# 
# def generate_changes(
#     client,
#     task,
#     selected_files,
#     previous_error=None
# ):
# 
#     files_text = "\n\n".join(
#         f"===== {name} =====\n{content}"
#         for name, content in selected_files.items()
#     )
# 
#     repair_info = ""
# 
#     if previous_error:
#         repair_info = f"""
# Previous attempt failed.
# 
# Error/test output:
# {previous_error}
# 
# Fix the problem causing this failure.
# """
# 
#     prompt = f"""
# You are an AI coding agent editing a real Python project.
# 
# Task:
# {task}
# 
# {repair_info}
# 
# Files to edit:
# 
# {files_text}
# 
# Return ONLY valid JSON in this exact format:
# 
# {{
#   "files": {{
#     "filename.py": "complete new file contents"
#   }}
# }}
# 
# Rules:
# - Return complete file contents.
# - Do not use Markdown fences.
# - Do not modify files that were not provided.
# - Preserve existing functionality.
# - Make the smallest reasonable change.
# - Ensure the resulting code is valid Python.
# """
# 
#     response = client.chat.completions.create(
#         model=MODEL,
#         messages=[
#             {
#                 "role": "system",
#                 "content": "Return only valid JSON."
#             },
#             {
#                 "role": "user",
#                 "content": prompt
#             }
#         ],
#         temperature=0
#     )
# 
#     return extract_json(response.choices[0].message.content)
# 
# 
# def make_backup(project):
#     backup = project.parent / f"{project.name}_backup"
# 
#     if backup.exists():
#         shutil.rmtree(backup)
# 
#     shutil.copytree(project, backup)
# 
#     return backup
# 
# 
# def show_diff(original, updated, filename):
# 
#     diff = difflib.unified_diff(
#         original.splitlines(),
#         updated.splitlines(),
#         fromfile=f"{filename} (before)",
#         tofile=f"{filename} (after)",
#         lineterm=""
#     )
# 
#     diff_text = "\n".join(diff)
# 
#     if diff_text:
#         print(diff_text)
#     else:
#         print(f"No changes proposed for {filename}.")
# 
# 
# def apply_changes(project, changes):
# 
#     for filename, content in changes.items():
# 
#         target = (project / filename).resolve()
# 
#         if not str(target).startswith(str(project.resolve())):
#             raise ValueError(
#                 f"Unsafe path rejected: {filename}"
#             )
# 
#         target.parent.mkdir(
#             parents=True,
#             exist_ok=True
#         )
# 
#         target.write_text(
#             content,
#             encoding="utf-8"
#         )
# 
# 
# def run_tests(project):
# 
#     commands = [
#         ["python", "-m", "pytest", "-q"],
#         ["python", "-m", "unittest", "discover"]
#     ]
# 
#     last_output = ""
# 
#     for command in commands:
# 
#         try:
# 
#             result = subprocess.run(
#                 command,
#                 cwd=project,
#                 capture_output=True,
#                 text=True,
#                 timeout=TIMEOUT
#             )
# 
#             output = (
#                 result.stdout +
#                 "\n" +
#                 result.stderr
#             ).strip()
# 
#             print(output)
# 
#             if result.returncode == 0:
#                 return True, output
# 
#             last_output = output
# 
#         except subprocess.TimeoutExpired:
#             last_output = (
#                 f"Test command timed out after {TIMEOUT} seconds."
#             )
# 
#         except FileNotFoundError:
#             continue
# 
#     return False, last_output
# 
# 
# def main():
# 
#     parser = argparse.ArgumentParser(
#         description="AI Coding Agent"
#     )
# 
#     parser.add_argument(
#         "--project",
#         required=True
#     )
# 
#     parser.add_argument(
#         "--task",
#         required=True
#     )
# 
#     parser.add_argument(
#         "--dry-run",
#         action="store_true"
#     )
# 
#     args = parser.parse_args()
# 
#     project = Path(args.project).resolve()
# 
#     if not project.exists():
#         print(f"❌ Project does not exist: {project}")
#         return
# 
#     print("\n" + "=" * 70)
#     print("🤖 AI CODING AGENT")
#     print("=" * 70)
# 
#     print(f"Project : {project}")
#     print(f"Task    : {args.task}")
#     print(f"Dry run : {args.dry_run}")
# 
#     print("=" * 70)
# 
#     client = get_client()
# 
#     print("\n📖 Reading project...")
# 
#     files = read_project(project)
# 
#     if not files:
#         print("❌ No Python files found.")
#         return
# 
#     print(f"Found {len(files)} Python files.")
# 
#     context = build_context(files)
# 
#     print("\n🧠 Planning changes...")
# 
#     plan = plan_changes(
#         client,
#         args.task,
#         context
#     )
# 
#     selected_names = plan.get(
#         "files_to_edit",
#         []
#     )
# 
#     print("\nFiles selected:")
#     for name in selected_names:
#         print(f"  • {name}")
# 
#     print("\nReason:")
#     print(plan.get("reason", ""))
# 
#     selected_files = {
#         name: files[name]
#         for name in selected_names
#         if name in files
#     }
# 
#     if not selected_files:
#         print("❌ No valid files selected.")
#         return
# 
#     backup = make_backup(project)
# 
#     print(f"\n💾 Backup created: {backup}")
# 
#     previous_error = None
# 
#     for attempt in range(1, MAX_ATTEMPTS + 1):
# 
#         print("\n" + "=" * 70)
#         print(f"🔄 ATTEMPT {attempt}/{MAX_ATTEMPTS}")
#         print("=" * 70)
# 
#         try:
# 
#             result = generate_changes(
#                 client,
#                 args.task,
#                 selected_files,
#                 previous_error
#             )
# 
#             changes = result.get("files", {})
# 
#             if not changes:
#                 print("❌ LLM returned no changes.")
#                 return
# 
#             print("\n📝 PROPOSED DIFF\n")
# 
#             for filename, new_content in changes.items():
# 
#                 old_content = selected_files.get(
#                     filename,
#                     ""
#                 )
# 
#                 print(f"\n--- {filename} ---")
# 
#                 show_diff(
#                     old_content,
#                     new_content,
#                     filename
#                 )
# 
#             if args.dry_run:
# 
#                 print("\n🔍 DRY RUN")
#                 print("No files were modified.")
# 
#                 return
# 
#             apply_changes(
#                 project,
#                 changes
#             )
# 
#             print("\n🧪 Running tests...")
# 
#             passed, output = run_tests(project)
# 
#             if passed:
# 
#                 print("\n" + "=" * 70)
#                 print("✅ SUCCESS")
#                 print("=" * 70)
# 
#                 print(
#                     f"Task completed successfully "
#                     f"on attempt {attempt}."
#                 )
# 
#                 return
# 
#             previous_error = output
# 
#             print("\n❌ TESTS FAILED")
# 
#         except Exception as e:
# 
#             previous_error = str(e)
# 
#             print(
#                 f"\n❌ Agent error: {e}"
#             )
# 
#     print("\n" + "=" * 70)
#     print("❌ FAILED AFTER 3 ATTEMPTS")
#     print("=" * 70)
# 
#     print(f"Backup available at: {backup}")
# 
# 
# if __name__ == "__main__":
#     main()

!python agent.py \
  --project ./demo_project \
  --task "Fix the average function so it correctly handles negative numbers" \
  --dry-run

from pathlib import Path

project = Path("/content/demo_project")
project.mkdir(parents=True, exist_ok=True)

(project / "calculator.py").write_text("""
def average(numbers):
    total = sum(numbers)
    return total / len(numbers)
""")

(project / "test_calculator.py").write_text("""
from calculator import average

def test_average():
    assert average([1, 2, 3]) == 2

def test_negative_numbers():
    assert average([-1, -2, -3]) == -2
""")

print("✅ Project created:", project)
print("Files:")
for f in project.iterdir():
    print(" -", f.name)

!ls -la /content/demo_project

!python /content/agent.py \
  --project /content/demo_project \
  --task "Fix the average function so it correctly handles negative numbers"